version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kom-product-service
    ports:
      - 4000:4000
    volumes:
      - ./config.json:/app/config.json